# Generated by Django 4.2.6 on 2023-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donarName', models.CharField(max_length=20)),
                ('phoneNum', models.IntegerField(max_length=14)),
                ('foodItem', models.CharField(max_length=50)),
                ('fooDescription', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='fooDonation/images')),
            ],
        ),
    ]
