# Generated by Django 4.2.6 on 2023-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Raw Food'), ('2', 'Packed Food'), ('3', 'Cooked Food')], default='1', max_length=30)),
                ('donarName', models.CharField(max_length=20)),
                ('donarEmail', models.EmailField(max_length=70)),
                ('phoneNum', models.CharField(max_length=70)),
                ('foodItem', models.CharField(max_length=50)),
                ('fooDescription', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_meal', models.CharField(max_length=30, null=True)),
                ('receiver_name', models.CharField(max_length=30)),
                ('receiver_num', models.CharField(default='', max_length=10)),
                ('receiver_email', models.CharField(default='', max_length=50)),
                ('receiver_address', models.CharField(max_length=70)),
                ('des', models.TextField()),
            ],
        ),
    ]
