# Generated by Django 4.2.6 on 2023-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='phoneNum',
            field=models.CharField(default='', max_length=70),
        ),
    ]
