# Generated by Django 4.2.6 on 2023-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0002_alter_donate_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donarEmail',
            field=models.EmailField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='donate',
            name='fooDescription',
            field=models.CharField(max_length=400),
        ),
    ]
