# Generated by Django 4.2.6 on 2023-11-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0002_alter_donate_donarname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Raw Food'), ('2', 'Packed Food'), ('3', 'Cooked Food')], default='1', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donarEmail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donarName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='fooDescription',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='foodItem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
