# Generated by Django 4.2.6 on 2023-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0003_alter_donate_address_alter_donate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donate',
            name='category',
            field=models.CharField(choices=[('1', 'Raw Food'), ('2', 'Packed Food'), ('3', 'Cooked Food')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donarEmail',
            field=models.EmailField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='donate',
            name='donarName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='donate',
            name='fooDescription',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='donate',
            name='foodItem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='phoneNum',
            field=models.CharField(default='', max_length=70),
        ),
    ]
