# Generated by Django 4.2.6 on 2023-10-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0003_donate_donaremail_alter_donate_foodescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='category',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
