# Generated by Django 4.2.6 on 2023-11-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0004_donate_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_meal', models.CharField(max_length=30, null=True)),
                ('receiver_name', models.CharField(max_length=20)),
                ('receiver_email', models.CharField(default='', max_length=20)),
                ('receiver_address', models.CharField(default='', max_length=40)),
                ('receiver_textArea', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
