# Generated by Django 4.2.6 on 2023-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0004_donate_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=140, null=True)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_email', models.CharField(default='', max_length=70)),
                ('receiver_num', models.CharField(default='', max_length=13)),
                ('receiver_address', models.CharField(max_length=100)),
                ('verify_des', models.CharField(max_length=500)),
            ],
        ),
    ]
