# Generated by Django 4.2.4 on 2023-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0005_alter_donate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='category',
            field=models.CharField(choices=[('Raw Food', 'Raw Food'), ('Packed Food', 'Packed Food'), ('Cooked Food', 'Cooked Food')], default='Raw Food', max_length=30),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_meal',
            field=models.CharField(choices=[('rosgula', 'rosgula'), ('golgapa', 'golgapa'), ('maggie', 'maggie'), ('meat', 'meat'), ('papdi chart', 'papdi chart'), ('pineapple', 'pineapple'), ('chaumeen', 'chaumeen'), ('kurkure', 'kurkure'), ('chips', 'chips'), ('chocolate', 'chocolate')], default='', max_length=30),
        ),
    ]
