# Generated by Django 4.2.6 on 2023-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0006_receiveruser_receiver_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_textArea',
            field=models.CharField(max_length=500),
        ),
    ]
