# Generated by Django 4.2.6 on 2024-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0006_alter_donate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveruser',
            name='category',
            field=models.CharField(choices=[('Raw Food', 'Raw Food'), ('Packed Food', 'Packed Food'), ('Cooked Food', 'Cooked Food')], default='Raw Food', max_length=30),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_meal',
            field=models.CharField(choices=[('aalu', 'aalu')], default='', max_length=30),
        ),
    ]
