# Generated by Django 4.2.6 on 2023-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0007_alter_receiveruser_receiver_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_num',
            field=models.CharField(default='', max_length=20),
        ),
    ]
