# Generated by Django 4.0.10 on 2024-01-08 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0008_receiveruser_timestamp_receiveruser_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Raw Food', 'Raw Food'), ('Packed Food', 'Packed Food'), ('Cooked Food', 'Cooked Food')], default='Raw Food', max_length=30)),
                ('donarName', models.CharField(default='', max_length=20)),
                ('donarEmail', models.EmailField(default='', max_length=70)),
                ('phoneNum', models.CharField(default='', max_length=70)),
                ('foodItem', models.CharField(default='', max_length=50)),
                ('fooDescription', models.CharField(default='', max_length=400)),
                ('address', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='receiveruser',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
