# Generated by Django 4.0.10 on 2024-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0009_donaruser_receiveruser_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_meal',
            field=models.CharField(choices=[], default='', max_length=30),
        ),
    ]
