# Generated by Django 4.0.10 on 2024-01-08 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0009_donate_timestamp_donate_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receiveruser',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
