# Generated by Django 4.0.10 on 2024-01-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0010_donate_publish_receiveruser_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
