# Generated by Django 4.2.4 on 2023-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0010_alter_receiveruser_receiver_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_num',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_textArea',
            field=models.CharField(default='', max_length=500),
        ),
    ]
