# Generated by Django 4.0.10 on 2024-01-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0013_donate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveruser',
            name='receiver_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fooDonationApp.donate'),
        ),
    ]
