# Generated by Django 4.2.4 on 2023-11-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0014_alter_receiveruser_receiver_textarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveruser',
            old_name='receiver_textArea',
            new_name='des',
        ),
    ]
