# Generated by Django 4.2.4 on 2023-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooDonationApp', '0015_rename_receiver_textarea_receiveruser_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='category',
            field=models.CharField(choices=[('1', 'Raw Food'), ('2', 'Packed Food'), ('3', 'Cooked Food')], default='1', max_length=30),
        ),
    ]
